# Generated by Django 4.0.3 on 2022-05-18 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('BirthDay', models.DateTimeField(default=datetime.datetime(2022, 5, 18, 20, 47, 26, 451857))),
                ('WorkName', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(max_length=11)),
                ('Special', models.CharField(max_length=100)),
                ('see', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Admin.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('BirthDay', models.DateTimeField()),
                ('WorkName', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(max_length=11)),
                ('reserved', models.BooleanField(default=False)),
                ('examin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Admin.doctor')),
                ('see', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Admin.admin')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationTicket',
            fields=[
                ('Code', models.IntegerField(primary_key=True, serialize=False)),
                ('PatientName', models.CharField(max_length=100)),
                ('PatientDoctor', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Disease', models.CharField(max_length=100)),
                ('State_of_treatement', models.BooleanField(default=False)),
                ('have', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Admin.patient')),
                ('write', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Admin.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Code', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('choose', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Admin.patient')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Admin.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('dep_Id', models.IntegerField()),
                ('day', models.CharField(max_length=10)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.department')),
            ],
        ),
    ]
