# Generated by Django 4.0.3 on 2022-05-18 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='BirthDay',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 20, 49, 21, 404962)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Phone',
            field=models.CharField(max_length=11),
        ),
    ]
