# Generated by Django 4.0.3 on 2022-05-18 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_doctor_birthday_alter_doctor_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='BirthDay',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 20, 52, 17, 844940)),
        ),
    ]
