# Generated by Django 4.0.3 on 2022-06-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_patient_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Feedback',
            new_name='FeedBack',
        ),
    ]
